### PR TITLE
return instagram object when posting instead of null

### PR DESCRIPTION
**Pull request by atpanos**

### CODE REVIEW

**Comment by ErrorxCode** [comment]
Instead, what you can do is check the success and failure of the result in the method body itself and then throw an exception if it fails.

**Comment by atpanos** [comment]
I need the id of the created post.
If I want to delete it in the future I have then the id stored.

**Comment by ErrorxCode** [comment]
Then change the type of `AsyncTask<Void>` to `AsyncTask<String>` and return post id from the response of api call.

**Comment by ErrorxCode** [comment]
Inactive!

**Pull request closed without merging**
